### ISSUE TITLE
Device Tree Overlay

### ISSUE THREAD

**Issue by edison369** [alanc98/rtems-cfs-demo#2]
Hi @alanc98 !!,
It's me, Edison, again, I didn't know how to contact you, that is why I made this other issue. Currently I am trying to use the SPI protocol for communication between the BBB and a RF module but I am having troubles with it. I noticed that using a device tree overlay you added a i2c device and I think I have to do the same in order to create a SPI device and be able to communicate the BBB with the RF module. The thing is that I am new to working with a device tree and I don't know how to make a device tree overlay. Please, would you be able to help me on how to make the device tree overlay? Or maybe do you know where can I read a guide? Because I found a guide but it is for a BBB with Linux 3.8 and in this guide they do everything from the command line in the BBB. I hope you can help me with this!

Sincerely,
Edison Martínez

**Comment by alanc98** [comment]
Hi @edison369 , If you have not seen this guide, I would start here:
https://learn.adafruit.com/introduction-to-the-beaglebone-black-device-tree/overview
Other resources I found:
https://beagleboard.org/blog/2022-02-15-using-device-tree-overlays-example-on-beaglebone-cape-add-on-boards
https://www.ofitselfso.com/BeagleNotes/Beaglebone_Black_And_Device_Tree_Overlays.php
I cannot claim to be an expert, but hopefully this will help you get started!
Alan

**Comment by edison369** [comment]
Thank you very much!! I will definitely take a look at this pages :) 
Have a nice day!

Edison
